[[redirects]]
from = "/assets/*"
to = "/404.html"
status = 404

[[redirects]]
from = "/src/*"
to = "/404.html"
status = 404

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
command = "npx vite build"
publish = "dist"